version: '3.3'

services:
        mqttgateway:
                build: .
                restart: unless-stopped
                environment:
                        - WEB_TELEMETRY_PORT=9337
                        - WEB_TELEMETRY_PATH=/metrics
                        - MQTT_BROKER_ADDRESS=tcp://IP_TO_YOUR_MQTT:1883
                        - MQTT_TOPIC=prometheus/#
                        - MQTT_PREFIX=prometheus
                        - MQTT_CLIENT_ID=mqtt2prometheus 
networks:
        default:
